# Common vars
availability_zone: melbourne-qh2-uom

# Volume
volumes:
  - vol_name: vol-2
    vol_size: 10

# Security group
security_groups:
  - name: ssh
    description: "Demo security group for SSH access"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  - name: http
    description: "Demo security group for HTTP"
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0

# Instance
instances:
  - name: testInstance
    volumes: 'vol-2'

instance_image: f8b79936-6616-4a22-b55d-0d0a1d27bceb
instance_key_name: mrc-key
instance_flavor: 	uom.mse.1c4g

ansible_user: ubuntu
ansible_ssh_private_key_file: ./config/mrc-key.pem