# Volume
volumes:
  - vol_name: vol-1
    vol_size: 100
  - vol_name: vol-2
    vol_size: 100
  - vol_name: vol-3
    vol_size: 100
  - vol_name: vol-4
    vol_size: 100

# Security group
security_groups:
  - name: ssh
    description: "Security group for SSH access"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  - name: http
    description: "Security group for HTTP"
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0
  - name: https
    description: "Security group for HTTPS"
    protocol: tcp
    port_range_min: 443
    port_range_max: 443
    remote_ip_prefix: 0.0.0.0/0
  - name: dash website
    description: "Security group for dash website"
    protocol: tcp
    port_range_min: 5000
    port_range_max: 5000
    remote_ip_prefix: 0.0.0.0/0
  - name: couchDB
    description: "Security group for couchDB"
    protocol: tcp
    port_range_min: 5984
    port_range_max: 5984
    remote_ip_prefix: 0.0.0.0/0

# Instance
instances:
  - name: instance-1
    volumes: 'vol-1'
  - name: instance-2
    volumes: 'vol-2'
  - name: instance-3
    volumes: 'vol-3'
  - name: instance-4
    volumes: 'vol-4'
