# Common vars
availability_zone: melbourne-qh2-uom

# Volume
volumes:
  - vol_name: vol-1
    vol_size: 100
  - vol_name: vol-2
    vol_size: 100
  - vol_name: vol-3
    vol_size: 100

# Security group
security_groups:
  - name: ssh
    description: "Security group for SSH access"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  - name: http
    description: "Security group for HTTPS"
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0
  - name: https
    description: "Security group for HTTPS"
    protocol: tcp
    port_range_min: 443
    port_range_max: 443
    remote_ip_prefix: 0.0.0.0/0
  - name: Dash website
    description: "Security group for Dash website"
    protocol: tcp
    port_range_min: 5000
    port_range_max: 5000
    remote_ip_prefix: 0.0.0.0/0
  - name: couchDB
    description: "Security group for couchDB"
    protocol: tcp
    port_range_min: 5984
    port_range_max: 5984
    remote_ip_prefix: 0.0.0.0/0
  # - name: all-ports-open
  #   description: "Open all ports for tcp connection"
  #   protocol: tcp
  #   port_range_min: 1
  #   port_range_max: 65535
  #   remote_ip_prefix: 0.0.0.0/0

# Instance
instances:
  - name: testInstance-1
    volumes: 'vol-1'
  - name: testInstance-2
    volumes: 'vol-2'
  - name: testInstance-3
    volumes: 'vol-3'

instance_image: f8b79936-6616-4a22-b55d-0d0a1d27bceb
instance_key_name: mrc-key
instance_flavor: 	uom.mse.1c4g

ansible_user: ubuntu
ansible_ssh_private_key_file: ./config/mrc-key.pem

git_repo: ./home/ubuntu/git-repo

# ansible_python_interpreter: /usr/local/bin/python3

github_user_name: mrc-user
github_user_password: unimelb2021

couchdb_container_name: couchdb
