# - name: Install json
#   become: yes
#   apt:
#     name: ['json']
#     state: latest
#     update_cache: yes

- name: Install shapely
  become: yes
  pip:
    name: ['shapely']
    state: latest

- name: Install jsonlines
  become: yes
  pip:
    name: ['jsonlines']
    state: latest

- name: Install python3-pip
  become: yes
  apt:
    name: ['python3-pip']
    state: latest
    update_cache: yes

- name: Install cloudant
  become: yes
  pip:
    name: ['cloudant']
    state: latest