<<<<<<< HEAD
- name: Create docker proxy file
  shell: |
    sudo mkdir -p /etc/systemd/system/docker.service.d
    sudo touch /etc/systemd/system/docker.service.d/http-proxy.conf

- name: Add proxy to the instance
  become: yes
  copy:
    dest: /etc/systemd/system/docker.service.d/http-proxy.conf
    content: |
      [Service]
      Environment="HTTP_PROXY=http://wwwproxy.unimelb.edu.au:8000/"
      Environment="HTTPS_PROXY=http://wwwproxy.unimelb.edu.au:8000/"
      Environment="NO_PROXY=localhost,127.0.0.1,localaddress,172.16.0.0/12,.melbourne.rc.nectar.org.au,.storage.unimelb.edu.au,.cloud.unimelb.edu.au"
      Environment="http_proxy=http://wwwproxy.unimelb.edu.au:8000/"
      Environment="https_proxy=http://wwwproxy.unimelb.edu.au:8000/"


- name: Create another docker proxy file
  shell: |
    sudo mkdir -p /home/ubuntu/.docker
    sudo touch /home/ubuntu/.docker/config.json

- name: Add another proxy to the instance
  become: yes
  copy:
    dest: /home/ubuntu/.docker/config.json
    content: |
      {
        "proxies":
        {
          "default":
          {
            "httpProxy": "http://wwwproxy.unimelb.edu.au:8000/",
            "httpsProxy": "http://wwwproxy.unimelb.edu.au:8000/",
            "noProxy": "localhost,127.0.0.1,localaddress,172.16.0.0/12,.melbourne.rc.nectar.org.au,.storage.unimelb.edu.au,.cloud.unimelb.edu.au"
          }
        }
      }

- name: Stop docker
  become: yes
  shell: sudo systemctl stop docker

- name: Reload docker daemon
  shell: sudo systemctl daemon-reload

- name: Start docker
  become: yes
  shell: sudo systemctl start docker

- name: Start a container with a couchdb
  become: yes
=======
# - name: Create docker proxy file
#   shell: |
#     sudo mkdir -p /etc/systemd/system/docker.service.d
#     sudo touch /etc/systemd/system/docker.service.d/http-proxy.conf

# - name: Add proxy to the instance
#   become: yes
#   copy:
#     dest: /etc/systemd/system/docker.service.d/http-proxy.conf
#     content: |
#       [Service]
#       Environment="HTTP_PROXY=http://wwwproxy.unimelb.edu.au:8000/"
#       Environment="HTTPS_PROXY=http://wwwproxy.unimelb.edu.au:8000/"
#       Environment="NO_PROXY=localhost,127.0.0.1,localaddress,172.16.0.0/12,.melbourne.rc.nectar.org.au,.storage.unimelb.edu.au,.cloud.unimelb.edu.au"
#       Environment="http_proxy=http://wwwproxy.unimelb.edu.au:8000/"
#       Environment="https_proxy=http://wwwproxy.unimelb.edu.au:8000/"


# - name: Create another docker proxy file
#   shell: |
#     sudo mkdir -p /home/ubuntu/.docker
#     sudo touch /home/ubuntu/.docker/config.json

# - name: Add another proxy to the instance
#   become: yes
#   copy:
#     dest: /home/ubuntu/.docker/config.json
#     content: |
#       {
#         "proxies":
#         {
#           "default":
#           {
#             "httpProxy": "http://wwwproxy.unimelb.edu.au:8000/",
#             "httpsProxy": "http://wwwproxy.unimelb.edu.au:8000/",
#             "noProxy": "localhost,127.0.0.1,localaddress,172.16.0.0/12,.melbourne.rc.nectar.org.au,.storage.unimelb.edu.au,.cloud.unimelb.edu.au"
#           }
#         }
#       }

# - name: Stop docker
#   become: yes
#   shell: sudo systemctl stop docker

# - name: Reload docker daemon
#   shell: sudo systemctl daemon-reload

# - name: Start docker
#   become: yes
#   shell: sudo systemctl start docker

- name: Start a container with a couchdb
  become: yes
>>>>>>> 0fb6052686848289e5a3fef9fab5737886ad90ef
  docker_container:
    name: "my-couchdb"
    image: "apache/couchdb:3.0"
    ports:
      - "5984:5984"
    env:
      COUCHDB_PASSWORD: "password"
      COUCHDB_USER: "admin"
      # NODENAME: "{{ ansible_host }}"
      # COUCHDB_SECRET: "{{ couchdb_cookie }}"