- name: Start a container with a couchdb
  become: yes
  docker_container:
    name: "my-couchdb"
    image: "apache/couchdb:3.0"
    ports:
      - "5984:5984"
    env:
      COUCHDB_PASSWORD: "password"
      COUCHDB_USER: "admin"