# - name: Remove docker
#   become: yes
#   shell: sudo apt-get remove docker docker-engine docker.io containerd runc
# - name: Install docker
#   shell: |
#     sudo apt-get install \
#     apt-transport-https \
#     ca-certificates \
#     curl \
#     gnupg \
#     lsb-release

# - name: Install apt transport https
#   shell: sudo apt install apt-transport-https ca-certificates curl software-properties-common

# - name: Add GPG key
#   shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

# - name: Add the Docker repository to APT sources
#   shell: sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"

- name: Install docker
  become: yes
  apt:
    name: ['docker.io']
    state: latest

- name: Install docker-compose
  become: yes
  apt:
    name: ['docker-compose']
    state: latest

# - name: Create docker proxy file
#   shell: |
#     sudo mkdir -p /etc/systemd/system/docker.service.d
#     sudo touch /etc/systemd/system/docker.service.d/http-proxy.conf


# - name: Add proxy to the instance
#   become: yes
#   copy:
#     dest: /etc/systemd/system/docker.service.d/http-proxy.conf
#     content: |
#       [Service]
#       Environment="HTTP_PROXY=http://wwwproxy.unimelb.edu.au:80/"
#       Environment="HTTPS_PROXY=http://wwwproxy.unimelb.edu.au:443/"
#       Environment="http_proxy=http://wwwproxy.unimelb.edu.au:80/"
#       Environment="https_proxy=http://wwwproxy.unimelb.edu.au:443/"
#       Environment="no_proxy=localhost,127.0.0.1,localaddress,172.16.0.0/12,.melbourne.rc.nectar.org.au,.storage.unimelb.edu.au,.cloud.unimelb.edu.au"


- name: Create docker proxy file
  shell: |
    sudo mkdir -p /etc/systemd/system/docker.service.d
    sudo touch /etc/systemd/system/docker.service.d/http-proxy.conf

- name: Add proxy to the instance
  become: yes
  copy:
    dest: /etc/systemd/system/docker.service.d/http-proxy.conf
    content: |
      [Service]
      Environment="HTTP_PROXY=http://wwwproxy.unimelb.edu.au:80/"
      Environment="HTTPS_PROXY=http://wwwproxy.unimelb.edu.au:443/"
      Environment="http_proxy=http://wwwproxy.unimelb.edu.au:80/"
      Environment="https_proxy=http://wwwproxy.unimelb.edu.au:443/"
      Environment="no_proxy=localhost,127.0.0.1,localaddress,172.16.0.0/12,.melbourne.rc.nectar.org.au,.storage.unimelb.edu.au,.cloud.unimelb.edu.au"



- name: Create another docker proxy file
  shell: |
    sudo mkdir -p ~/.docker
    sudo touch ~/.docker/config.json

- name: Add another proxy to the instance
  become: yes
  copy:
    dest: ~/.docker/config.json
    content: |
      {
        "proxies":
        {
          "default":
          {
            "httpProxy": "http://wwwproxy.unimelb.edu.au:8000/",
            "httpsProxy": "http://wwwproxy.unimelb.edu.au:8000/",
            "noProxy": "localhost,127.0.0.1,localaddress,172.16.0.0/12,.melbourne.rc.nectar.org.au,.storage.unimelb.edu.au,.cloud.unimelb.edu.au"
          }
        }
      }


# {
#   "proxies":
#   {
#     "default":
#     {
#       "HTTP_PROXY": "http://wwwproxy.unimelb.edu.au:8000/",
#       "HTTPS_PROXY": "http://wwwproxy.unimelb.edu.au:8000/",
#       "http_proxy": "http://wwwproxy.unimelb.edu.au:8000/",
#       "https_proxy": "http://wwwproxy.unimelb.edu.au:8000/",
#       "no_proxy": "localhost,127.0.0.1,localaddress,172.16.0.0/12,.melbourne.rc.nectar.org.au,.storage.unimelb.edu.au,.cloud.unimelb.edu.au"
#     }
#   }
# }


# "httpProxy": "http://wwwproxy.unimelb.edu.au:8000/",
# "httpsProxy": "http://wwwproxy.unimelb.edu.au:8000/",


# "HTTP_PROXY": "http://wwwproxy.unimelb.edu.au:8000/",
# "HTTPS_PROXY": "http://wwwproxy.unimelb.edu.au:8000/",
# "http_proxy": "http://wwwproxy.unimelb.edu.au:8000/",
# "https_proxy": "http://wwwproxy.unimelb.edu.au:8000/",


- name: Remove previous PID file
  become: yes
  shell: rm -rf /var/run/docker.pid

# - name:
#   become: yes
#   shell: ps axf | grep docker | grep -v grep | awk '{print "kill -9 " $1}' | sudo sh 

- name: Stop docker
  become: yes
  shell: sudo systemctl stop docker

- name: Start docker
  become: yes
  shell: sudo systemctl start docker

# - name: Start docker
#   become: yes
#   shell: |
#     sudo dockerd --debug \
#     --tls=true \
#     --tlscert=/var/docker/server.pem \
#     --tlskey=/var/docker/serverkey.pem \
#     --host tcp://192.168.59.3:2376

- name: Reload docker daemon
  shell: sudo systemctl daemon-reload

- name: Restart docker
  shell: sudo systemctl restart docker

# - name: Add user to docker group
#   become: yes
#   shell: sudo usermod -aG docker root

- name: Run couchDB docker compose
  become: yes
  shell: |
    chdir=/home/ubuntu/COMPCOMP90024CCC_ASS2/webdocker/
    sudo docker-compose up -d