---

# Install python
- name: Install pip
  become: yes
  apt:
    name: ['python3-pip']
    state: latest
    update_cache: yes

# Update python
- name: Update pip
  become: yes
  pip:
    name: ['pip']
    state: latest

# Install couchdb
- name: Install couchdb
  become: yes
  pip:
    name: ['couchdb']
    state: latest

# Install docker
- name: Install docker
  become: yes
  apt:
    name: ['docker']
    state:  latest

