---
- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: yes
    update_cache: yes

- name: Delete content & directory
  file:
    state: absent
    path: '{{ git_repo }}'

- name: Get updated files from git repository   
  shell: git clone https://mrc-user:unimelb2021@github.com/rexding97/COMP90024CCC_ASS2.git /home/ubuntu/COMPCOMP90024CCC_ASS2