version: '3.7'
services:

  web:
    build: 
      context: ./
    container_name: ${COMPOSE_PROJECT_NAME}_web
    hostname: ${COMPOSE_PROJECT_NAME}_web
    env_file:
      - web-variables.env
    restart: always
    ports:
      - 5000:80
    networks:
      - network 
      
networks:
  network:
    driver: bridge
