---
- hosts: database
  vars:
    ansible_python_interpreter: /usr/bin/python3
  vars_files:
    - host_vars/mrc.yaml
    - host_vars/config.yaml
  gather_facts: true

  roles:
    - role: deploy-couchdb
    # - role: couchdb-docker-compose
    # - role: run-crawler
    - role: deploy-couchdb-cluster
