---
- hosts: crawler
  vars:
    ansible_python_interpreter: /usr/bin/python3
  vars_files:
    - host_vars/mrc.yaml
    - host_vars/config.yaml
  gather_facts: true

  roles:
    - role: run-crawler
