# - set_fact:
#     fs_ip_addr: "{{ (lookup('file', '../inventory/host.ini').splitlines()|
#                     list|
#                     select('search', 'database')|
#                     list|
#                     first).split().0 }}"

# - name: Unzip sentiment_analysis
#   shell: |
#     cd /home/ubuntu/COMPCOMP90024CCC_ASS2/crawler/sentiment_analysis
#     7z x sentiment_analysis.7z 

- name: Delete nlp.model
  file:
    state: absent
    path: /home/ubuntu/COMPCOMP90024CCC_ASS2/crawler/sentiment_analysis/nlp.model

- name: Delete ./word_tokenizer.pkl
  file:
    state: absent
    path: /home/ubuntu/COMPCOMP90024CCC_ASS2/crawler/sentiment_analysis/./word_tokenizer.pkl

- name: Unzip sentiment_analysis
  shell: |
    cd /home/ubuntu/COMPCOMP90024CCC_ASS2/crawler/sentiment_analysis
    7z x sentiment_analysis.7z 



- name: Run crawler
  shell: |
    cd /home/ubuntu/COMPCOMP90024CCC_ASS2/crawler
    nohup python3 crawler_stream.py admin password http://{{ groups['database'][0] }}:5984 > output.log  &
  async: 45
  