- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: yes
    update_cache: yes

# - name: Login Docker Hub
#   shell: docker login -u a85913658@gmail.com -p comp90024ass2

- name: Pull dash image from Docker Hub
  shell: docker pull comp90024ass2/test-docker-compose
  ignore_errors: yes

# - name: Pull dash image from Docker Hub
#   docker_image:
#     name: comp90024ass2/test-docker-compose

# - name: Stop dash image
#   shell: docker stop comp90024ass2/test-docker-compose
#   ignore_errors: yes

# - name: Run dash image
#   shell: docker run -d -p 5000:80 comp90024ass2/test-docker-compose
#   ignore_errors: yes

- name: Stop docker container
  shell: docker stop frontend
  ignore_errors: yes

- name: Run dash image
  docker_container:
    name: "frontend"
    image: comp90024ass2/test-docker-compose
    ports:
      - "5000:80"