# - name: Run couchDB docker compose
#   become: yes
#   shell: |
#     chdir=/home/ubuntu/COMPCOMP90024CCC_ASS2/webdocker/
#     sudo docker-compose up -d

- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: yes
    update_cache: yes

- name: Pull dash image from Docker Hub
  shell: docker pull comp90024ass2/test-docker-compose
  ignore_errors: yes

# - name: Stop docker container
#   shell: docker stop $(docker ps -a -q --filter ancestor=comp90024ass2/test-docker-compose)

- name: Run dash image
  shell: docker run -d -p 5000:80 comp90024ass2/test-docker-compose
  ignore_errors: yes

# - name: Start dash using docker container
#   become: yes
#   docker_container:
#     name: "my-dash"
#     image: "comp90024ass2/test-docker-compose"
#     ports:
#       - "5000:80"
#     state: present